apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
metadata:
  creationTimestamp: "2024-09-12T13:23:36Z"
  managedFields:
  - apiVersion: choreo.kform.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:code:
          f:reconciler.star: {}
        f:for:
          f:group: {}
          f:kind: {}
          f:selector: {}
          f:version: {}
        f:type: {}
      f:status: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-09-12T13:23:36Z"
  name: infra.kuid.dev.endpoints.endpoint
  resourceVersion: "0"
  uid: 71e2e3e6-62bf-4a31-8df4-2eff7d21135b
spec:
  code:
    reconciler.star: |-
      finalizer = "endpoint.infra.kuid.dev/ready"
      conditionType = "Ready"

      def reconcile(endpoint):
        return reconcile_result(endpoint, False, 0, conditionType, "", False)
  for:
    group: infra.kuid.dev
    kind: Endpoint
    selector: {}
    version: v1alpha1
  type: starlark
status: {}
